### ISSUE TITLE
@inheritDoc has no value

### ISSUE THREAD

**Issue by szepeviktor** [Underpin-WP/underpin#8]
`@inheritDoc` may be deleted in 2020.

Plus we have some `@var inheritDoc` to be removed too.

**Comment by alexstandiford** [comment]
I know this sounds crazy, but I like to keep these because IDE's still automatically link to the parent method when they're in-place. Although they don't provide any actual _value_ to PHPDoc, I do think they help people, at a glance, understand that the documented method is actually inherited by the parent.

That being said, it's downright likely that there's a better way to express what I just said, I just haven't looked.

**Comment by szepeviktor** [comment]
> because IDE's still automatically link to the parent method when they're in-place

Switch to a modern IDE :)
